resource_types:
  - name: concourse-bitbucket-pullrequest
    type: docker-image
    source:
      repository: de.icr.io/cbp-development-registry/concourse-bitbucket-pullrequest-resource
      username: ((container-registry.username))
      password: ((container-registry.password))
  - name: slack-notification
    type: docker-image
    source:
      repository: de.icr.io/cbp-development-registry/cfcommunity/slack-notification-resource
      tag: v1.5.0
      username: ((container-registry.username))
      password: ((container-registry.password))

resources:
  - name: repo
    type: git
    source:
      uri: ssh://git@bitbucket.cic-garage.com:8000/ten/json-to-xml-converter.git
      branch: master
      private_key: ((bitbucket.private-key))
  - name: version
    type: semver
    source:
      initial_version: 0.1.0
      driver: git
      private_key: ((bitbucket.private-key))
      git_user: "Concourse <Concourse.CBP@nl.ibm.com>"
      file: version
      branch: version
      uri: ssh://git@bitbucket.cic-garage.com:8000/ten/json-to-xml-converter.git
  - name: pullrequest
    type: concourse-bitbucket-pullrequest
    source:
      username: ((bitbucket.username))
      password: ((bitbucket.password))
      uri: http://bitbucket.cic-garage.com/scm/ten/json-to-xml-converter.git
      skip_ssl_verification: true
      only_for_branch: 'master'
      create_comments: true
  - name: docker-dind-image
    type: docker-image
    source:
      repository: de.icr.io/cbp-development-registry/dind-with-bx-git-kubectl-and-python
      username: ((container-registry.username))
      password: ((container-registry.password))
      tag: "1.0"
    check_every: 15m
  - name: image
    type: docker-image
    source:
      repository: de.icr.io/cbp-development-registry/json-to-xml-converter
      username: ((container-registry.username))
      password: ((container-registry.password))
  - name: cbp-repo
    type: git
    source:
      uri: ssh://git@bitbucket.cic-garage.com:8000/ten/cbp.git
      branch: master
      private_key: ((bitbucket.private-key))
    check_every: 15m
  - name: base-image
    type: docker-image
    source:
      repository: de.icr.io/cbp-development-registry/base-application-image
      username: ((container-registry.username))
      password: ((container-registry.password))
      tag: 0.7.0
    check_every: 15m
  - name: git-image
    type: docker-image
    source:
      repository: de.icr.io/cbp-development-registry/dind-with-bx-git-kubectl-and-python
      username: ((container-registry.username))
      password: ((container-registry.password))
      tag: "0.2.0"
    check_every: 15m
  - name: daily-trigger
    type: time
    icon: clock-outline
    source:
      start: 06:00
      stop: 00:00
      location: Europe/Amsterdam
    check_every: 15m
  - name: slack-alert
    type: slack-notification
    source:
      url: ((slack.url))
    check_every: 15m
  - name: slack-new-pr-alert
    type: slack-notification
    source:
      url: ((slack.open-prs-url))
    check_every: 15m

jobs:
  - name: fix-vulnerabilities
    build_logs_to_retain: 50
    max_in_flight: 1
    plan:
      - get: daily-trigger
        trigger: true
      - in_parallel:
          - get: repo
          - get: cbp-repo
            params:
              submodules: none
          - get: base-image
          - get: git-image
      - task: checkout-npm-audit-fix-branch
        image: git-image
        file: cbp-repo/ci/tasks/checkout-npm-fix-branch.yaml
        params:
          private_key: ((bitbucket.private-key))
          bitbucket_username: ((bitbucket.username))
          bitbucket_password: ((bitbucket.password))
          project: TEN
          repository: json-to-xml-converter
          bitbucket_url: ((bitbucket.url))
      - task: npm-audit-fix
        image: base-image
        file: cbp-repo/ci/tasks/npm-audit-fix.yaml
        input_mapping:
          repo: checked-out-repo
        params:
          PACKAGE_JSON_DIRECTORY: "." # package.json is located in root of the repository
      - try:
          task: create-pull-request
          image: git-image
          file: cbp-repo/ci/tasks/create-pullrequest.yaml
          params:
            private_key: ((bitbucket.private-key))
            bitbucket_username: ((bitbucket.username))
            bitbucket_password: ((bitbucket.password))
            project: TEN
            repository: json-to-xml-converter
            bitbucket_url: ((bitbucket.url))
          input_mapping:
            repo: updated-repo
          on_success:
            put: slack-new-pr-alert
            params:
              icon_emoji: ":robot_face:"
              username: "'npm audit fix' pr"
              text_file: output/created-pr-message.txt
    on_failure:
      put: slack-alert
      params:
        icon_emoji: ":robot_face:"
        username: "fix-vulnerabilities bot"
        text: |
          <!here> Running the fix-vulnerabilities job for json-to-xml-converter has failed. Check it out at:
          https://concourse.cic-garage.com/teams/tennet-cbp/pipelines/json-to-xml-converter/jobs/fix-vulnerabilities/builds/$BUILD_NAME

  - name: build-pullrequest
    build_logs_to_retain: 50
    max_in_flight: 1
    plan:
      - do:
        - aggregate:
          - get: repo
            resource: pullrequest
            trigger: true
            version: every
          - get: docker-dind-image
        - put: pullrequest
          params:
            path: repo
            status: pending
            build_key: json-to-xml-converter-pull-request
        - task: version
          image: docker-dind-image
          file: repo/ci/tasks/pullrequest-version.yaml
        - put: image
          params:
            build: ./repo
            tag_file: version/version
            cache: true
            cache_tag: latest
          get_params:
            skip_download: true
        - put: pullrequest
          params:
            path: repo
            status: success
            build_key: json-to-xml-converter-pull-request
        on_failure:
          put: pullrequest
          params:
            path: repo
            status: failure
            build_key: json-to-xml-converter-pull-request

  - name: build
    max_in_flight: 1
    plan:
      - get: repo
        trigger: true
      - get: version
        params:
          bump: minor
      - put: image
        params:
          build: ./repo
          tag_file: version/version
          tag_as_latest: true
        get_params:
          skip_download: true
      - put: version
        params:
          file: version/version
      - put: repo
        params:
          repository: repo
          tag: version/version
